import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { getServerEnv } from "@/lib/env";
import { geminiGenerateText } from "@/lib/integrations/gemini";
import type { Language } from "@/lib/language";
import type { Post } from "@/lib/types";

export type JaniceSummary = {
  // Localized card title, e.g. "Janice executive summary" / "Janice 行政摘要".
  title: string;
  headline: string;
  bullets: { label: string; text: string }[];
  // "llm" = generated by Gemini; "heuristic" = keyword fallback. Shown in UI so
  // Alvie never mistakes a keyword guess for real analysis.
  mode: "llm" | "heuristic";
  // Localized "keyword draft" note, present on heuristic summaries only.
  draftNote?: string;
};

const LABELS: Record<Language, { title: string; keyPoint: string; implication: string; action: string; draft: string }> = {
  en: {
    title: "Janice executive summary",
    keyPoint: "Key point",
    implication: "Implication for Alvie",
    action: "Recommended action",
    draft: "keyword draft — no LLM key",
  },
  yue: {
    title: "Janice 行政摘要",
    keyPoint: "重點",
    implication: "對 Alvie 嘅意義",
    action: "建議行動",
    draft: "關鍵字草稿 — 未有 LLM key",
  },
};

export function draftLabel(language: Language): string {
  return LABELS[language].draft;
}

const storePath = join(process.cwd(), ".hermes", "janice-summaries.json");

// Memory cache survives across requests in one server process (and warm
// serverless instances); disk cache survives restarts where the FS is writable.
// Keys are `${postId}:${language}` so EN and 廣東話 summaries never collide.
const memoryCache = new Map<string, JaniceSummary>();
let diskLoaded = false;

async function loadDiskCache(): Promise<void> {
  if (diskLoaded) return;
  diskLoaded = true;
  try {
    const stored = JSON.parse(await readFile(storePath, "utf8")) as Record<string, JaniceSummary>;
    for (const [key, summary] of Object.entries(stored)) {
      // Ignore entries from the pre-localization schema (no title / no lang key).
      if (key.includes(":") && summary.title && !memoryCache.has(key)) {
        memoryCache.set(key, summary);
      }
    }
  } catch {
    // No disk cache yet (or read-only FS) — memory cache only.
  }
}

async function persistDiskCache(): Promise<void> {
  try {
    await mkdir(join(process.cwd(), ".hermes"), { recursive: true });
    await writeFile(storePath, `${JSON.stringify(Object.fromEntries(memoryCache), null, 2)}\n`);
  } catch {
    // Read-only FS (Vercel): memory cache still works for warm instances.
  }
}

const BATCH_PROMPT = `You are Janice, Alvie's chief-of-staff analyst. Alvie is an ex-Meta Client Partner in Hong Kong pursuing: a Big Tech offer, a Pokemon TCG investment platform, CityU lecturing (social media), and a faceless AI passive-income line.

For EACH post below, write an executive summary. Return ONLY a JSON array, one object per post, schema:
[{"id":"<post id>","headline":"<max 12 words, the single takeaway>","keyPoint":"<what the post actually says/shows>","implication":"<why it matters to Alvie's goals, be specific>","action":"<one concrete next step>"}]

Rules: be blunt, no hype, no padding. If a post is low-value, say so in the headline and recommend ignoring it. Never invent facts not in the post text.
{LANGUAGE_RULE}

Posts:
{POSTS}`;

const LANGUAGE_RULE: Record<Language, string> = {
  en: "Write headline, keyPoint, implication, and action in English.",
  yue: "headline、keyPoint、implication、action 全部用香港廣東話口語寫（用「係、唔、嘅、喺、俾」呢類字，唔好用書面中文），JSON keys 保持英文。",
};

function parseBatchResponse(raw: string, language: Language): Map<string, JaniceSummary> {
  const labels = LABELS[language];
  const parsed = new Map<string, JaniceSummary>();
  const jsonText = raw.replace(/^```(?:json)?/m, "").replace(/```\s*$/m, "").trim();
  try {
    const items = JSON.parse(jsonText) as {
      id?: string; headline?: string; keyPoint?: string; implication?: string; action?: string;
    }[];
    if (!Array.isArray(items)) return parsed;
    for (const item of items) {
      if (!item.id || !item.headline) continue;
      const bullets = [
        item.keyPoint ? { label: labels.keyPoint, text: item.keyPoint } : null,
        item.implication ? { label: labels.implication, text: item.implication } : null,
        item.action ? { label: labels.action, text: item.action } : null,
      ].filter((bullet): bullet is { label: string; text: string } => bullet !== null);
      if (bullets.length) {
        parsed.set(item.id, { title: labels.title, headline: item.headline, bullets, mode: "llm" });
      }
    }
  } catch {
    // Malformed LLM output → callers fall back to heuristic.
  }
  return parsed;
}

// Keyword fallback rules, bilingual. Body copy lives here; labels come from LABELS.
const HEURISTIC_RULES: {
  match: (text: string, lower: string) => boolean;
  en: { headline: string; keyPoint: string; implication: string; action: string };
  yue: { headline: string; keyPoint: string; implication: string; action: string };
}[] = [
  {
    match: (text, lower) => lower.includes("course") || text.includes("課程") || text.includes("證書"),
    en: {
      headline: "AI learning / career-capital reference.",
      keyPoint: "Structured learning content (course / certificate) that maps to a concrete skill.",
      implication: "Certificates and named skills strengthen Big Tech interview positioning.",
      action: "Tag Use for Career and extract 1 interview-ready example from it.",
    },
    yue: {
      headline: "AI 學習／職涯資本參考。",
      keyPoint: "有系統嘅學習內容（課程／證書），對應到一項具體技能。",
      implication: "證書同具名技能可以加強 Big Tech 面試定位。",
      action: "標做 Use for Career，抽 1 個面試可用嘅例子出嚟。",
    },
  },
  {
    match: (_text, lower) => lower.includes("prompt") || lower.includes("social media manager") || lower.includes("followers"),
    en: {
      headline: "Creator-growth playbook reference.",
      keyPoint: "A repeatable AI workflow for content output or audience growth.",
      implication: "Feeds the faceless passive-income line without personal-brand exposure.",
      action: "Test the workflow once before trusting its claimed results.",
    },
    yue: {
      headline: "創作者增長 playbook 參考。",
      keyPoint: "一個可重複用嘅 AI workflow，做內容輸出或者觀眾增長。",
      implication: "可以餵入 faceless 被動收入線，唔使露面。",
      action: "先自己試跑一次，唔好照信佢聲稱嘅成效。",
    },
  },
  {
    match: (text, lower) => lower.includes("vibe code") || lower.includes("cron") || lower.includes("skill") || text.includes("自動"),
    en: {
      headline: "Automation / system-building lesson.",
      keyPoint: "The durable value is the repeatable workflow, not the one-off tool.",
      implication: "Candidate pattern for the AI-agent execution stack.",
      action: "Note which step is automatable and add it to the build backlog.",
    },
    yue: {
      headline: "自動化／系統建設課一堂。",
      keyPoint: "真正有價值嘅係可重複嘅 workflow，唔係嗰個一次性工具。",
      implication: "可以考慮納入 AI agent 執行架構嘅 pattern。",
      action: "記低邊一步可以自動化，加入 build backlog。",
    },
  },
  {
    match: (text) => text.includes("算命") || text.includes("八字") || text.includes("紫微"),
    en: {
      headline: "Consumer AI trend signal.",
      keyPoint: "AI packaged as entertainment / identity / self-discovery drives mass attention.",
      implication: "Market signal for consumer-product trends, not a build recommendation.",
      action: "Track whether this format monetizes or stays a novelty.",
    },
    yue: {
      headline: "消費者 AI 趨勢信號。",
      keyPoint: "AI 包裝成娛樂／身份／自我探索，就會有大量注意力。",
      implication: "係 consumer product 趨勢信號，唔係叫你去起一個。",
      action: "留意呢個格式有冇真收入，定只係一時新鮮。",
    },
  },
];

export function heuristicSummary(post: Post, language: Language = "en"): JaniceSummary {
  const labels = LABELS[language];
  const text = post.text.replace(/\s+/g, " ").trim();
  const lower = text.toLowerCase();

  const build = (copy: { headline: string; keyPoint: string; implication: string; action: string }): JaniceSummary => ({
    mode: "heuristic",
    draftNote: labels.draft,
    title: labels.title,
    headline: copy.headline,
    bullets: [
      { label: labels.keyPoint, text: copy.keyPoint },
      { label: labels.implication, text: copy.implication },
      { label: labels.action, text: copy.action },
    ],
  });

  if (!text) {
    return build(language === "yue"
      ? {
          headline: "已儲存嘅參考，暫時未抽到內文。",
          keyPoint: "Atlas 抽唔到呢個 post 嘅文字，價值未經核實。",
          implication: "未開過原文之前，唔好基於佢做任何嘢。",
          action: "開返原文 link，再決定標籤定刪除。",
        }
      : {
          headline: "Saved reference with no extracted caption yet.",
          keyPoint: "Atlas could not extract text for this post, so its value is unverified.",
          implication: "Do not build on it until the source has been opened and read.",
          action: "Open the source link, then tag or delete it.",
        });
  }

  const rule = HEURISTIC_RULES.find((r) => r.match(text, lower));
  if (rule) {
    return build(rule[language]);
  }

  return {
    mode: "heuristic",
    draftNote: labels.draft,
    title: labels.title,
    headline: `${text.slice(0, 110)}${text.length > 110 ? "…" : ""}`,
    bullets: language === "yue"
      ? [
          { label: labels.keyPoint, text: "未有配對到嘅 pattern — 摘要顯示原文。" },
          { label: labels.action, text: "開返原文並加標籤，等之後嘅摘要準啲。" },
        ]
      : [
          { label: labels.keyPoint, text: "No matched pattern yet — summary shows the raw caption." },
          { label: labels.action, text: "Open the source and tag it so future summaries improve." },
        ],
  };
}

/**
 * Batched Janice summaries in the viewer's language: cached (memory + .hermes
 * disk, keyed post+language), one Gemini call for all uncached posts, heuristic
 * fallback when no GEMINI_API_KEY or the call fails.
 */
export async function getJaniceSummaries(posts: Post[], language: Language = "en"): Promise<Map<string, JaniceSummary>> {
  await loadDiskCache();
  const result = new Map<string, JaniceSummary>();
  const misses: Post[] = [];

  for (const post of posts) {
    const cached = memoryCache.get(`${post.id}:${language}`);
    if (cached && cached.mode === "llm") {
      result.set(post.id, cached);
    } else {
      misses.push(post);
    }
  }

  const { GEMINI_API_KEY } = getServerEnv();
  if (misses.length && GEMINI_API_KEY) {
    // Cap batch size to keep the prompt inside a sane token budget.
    const batch = misses.slice(0, 40);
    const payload = batch
      .map((post) => `id: ${post.id}\nsource: ${post.source} @${post.authorHandle}\ntext: ${post.text.replace(/\s+/g, " ").slice(0, 600)}`)
      .join("\n---\n");
    const response = await geminiGenerateText(
      GEMINI_API_KEY,
      [{ text: BATCH_PROMPT.replace("{LANGUAGE_RULE}", LANGUAGE_RULE[language]).replace("{POSTS}", payload) }],
      { temperature: 0.2, maxOutputTokens: 8000 },
    );
    if (response.ok) {
      const parsed = parseBatchResponse(response.text, language);
      for (const [id, summary] of parsed) {
        memoryCache.set(`${id}:${language}`, summary);
        result.set(id, summary);
      }
      if (parsed.size) {
        await persistDiskCache();
      }
    }
  }

  for (const post of posts) {
    if (!result.has(post.id)) {
      result.set(post.id, memoryCache.get(`${post.id}:${language}`) ?? heuristicSummary(post, language));
    }
  }

  return result;
}
