import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { getServerEnv } from "@/lib/env";
import { geminiGenerateText } from "@/lib/integrations/gemini";
import type { Post } from "@/lib/types";

export type JaniceSummary = {
  headline: string;
  bullets: { label: string; text: string }[];
  // "llm" = generated by Gemini; "heuristic" = keyword fallback. Shown in UI so
  // Alvie never mistakes a keyword guess for real analysis.
  mode: "llm" | "heuristic";
};

const storePath = join(process.cwd(), ".hermes", "janice-summaries.json");

// Memory cache survives across requests in one server process (and warm
// serverless instances); disk cache survives restarts where the FS is writable.
const memoryCache = new Map<string, JaniceSummary>();
let diskLoaded = false;

async function loadDiskCache(): Promise<void> {
  if (diskLoaded) return;
  diskLoaded = true;
  try {
    const stored = JSON.parse(await readFile(storePath, "utf8")) as Record<string, JaniceSummary>;
    for (const [id, summary] of Object.entries(stored)) {
      if (!memoryCache.has(id)) memoryCache.set(id, summary);
    }
  } catch {
    // No disk cache yet (or read-only FS) — memory cache only.
  }
}

async function persistDiskCache(): Promise<void> {
  try {
    await mkdir(join(process.cwd(), ".hermes"), { recursive: true });
    await writeFile(storePath, `${JSON.stringify(Object.fromEntries(memoryCache), null, 2)}\n`);
  } catch {
    // Read-only FS (Vercel): memory cache still works for warm instances.
  }
}

const BATCH_PROMPT = `You are Janice, Alvie's chief-of-staff analyst. Alvie is an ex-Meta Client Partner in Hong Kong pursuing: a Big Tech offer, a Pokemon TCG investment platform, CityU lecturing (social media), and a faceless AI passive-income line.

For EACH post below, write an executive summary. Return ONLY a JSON array, one object per post, schema:
[{"id":"<post id>","headline":"<max 12 words, the single takeaway>","keyPoint":"<what the post actually says/shows>","implication":"<why it matters to Alvie's goals, be specific>","action":"<one concrete next step>"}]

Rules: be blunt, no hype, no padding. If a post is low-value, say so in the headline and recommend ignoring it. Never invent facts not in the post text.

Posts:
{POSTS}`;

function parseBatchResponse(raw: string): Map<string, JaniceSummary> {
  const parsed = new Map<string, JaniceSummary>();
  const jsonText = raw.replace(/^```(?:json)?/m, "").replace(/```\s*$/m, "").trim();
  try {
    const items = JSON.parse(jsonText) as {
      id?: string; headline?: string; keyPoint?: string; implication?: string; action?: string;
    }[];
    if (!Array.isArray(items)) return parsed;
    for (const item of items) {
      if (!item.id || !item.headline) continue;
      const bullets = [
        item.keyPoint ? { label: "Key point", text: item.keyPoint } : null,
        item.implication ? { label: "Implication for Alvie", text: item.implication } : null,
        item.action ? { label: "Recommended action", text: item.action } : null,
      ].filter((bullet): bullet is { label: string; text: string } => bullet !== null);
      if (bullets.length) {
        parsed.set(item.id, { headline: item.headline, bullets, mode: "llm" });
      }
    }
  } catch {
    // Malformed LLM output → callers fall back to heuristic.
  }
  return parsed;
}

export function heuristicSummary(post: Post): JaniceSummary {
  const text = post.text.replace(/\s+/g, " ").trim();
  const lower = text.toLowerCase();

  if (!text) {
    return {
      mode: "heuristic",
      headline: "Saved reference with no extracted caption yet.",
      bullets: [
        { label: "Key point", text: "Atlas could not extract text for this post, so its value is unverified." },
        { label: "Implication for Alvie", text: "Do not build on it until the source has been opened and read." },
        { label: "Recommended action", text: "Open the source link, then tag or delete it." },
      ],
    };
  }

  if (lower.includes("course") || text.includes("課程") || text.includes("證書")) {
    return {
      mode: "heuristic",
      headline: "AI learning / career-capital reference.",
      bullets: [
        { label: "Key point", text: "Structured learning content (course / certificate) that maps to a concrete skill." },
        { label: "Implication for Alvie", text: "Certificates and named skills strengthen Big Tech interview positioning." },
        { label: "Recommended action", text: "Tag Use for Career and extract 1 interview-ready example from it." },
      ],
    };
  }

  if (lower.includes("prompt") || lower.includes("social media manager") || lower.includes("followers")) {
    return {
      mode: "heuristic",
      headline: "Creator-growth playbook reference.",
      bullets: [
        { label: "Key point", text: "A repeatable AI workflow for content output or audience growth." },
        { label: "Implication for Alvie", text: "Feeds the faceless passive-income line without personal-brand exposure." },
        { label: "Recommended action", text: "Test the workflow once before trusting its claimed results." },
      ],
    };
  }

  if (lower.includes("vibe code") || lower.includes("cron") || lower.includes("skill") || text.includes("自動")) {
    return {
      mode: "heuristic",
      headline: "Automation / system-building lesson.",
      bullets: [
        { label: "Key point", text: "The durable value is the repeatable workflow, not the one-off tool." },
        { label: "Implication for Alvie", text: "Candidate pattern for the AI-agent execution stack." },
        { label: "Recommended action", text: "Note which step is automatable and add it to the build backlog." },
      ],
    };
  }

  if (text.includes("算命") || text.includes("八字") || text.includes("紫微")) {
    return {
      mode: "heuristic",
      headline: "Consumer AI trend signal.",
      bullets: [
        { label: "Key point", text: "AI packaged as entertainment / identity / self-discovery drives mass attention." },
        { label: "Implication for Alvie", text: "Market signal for consumer-product trends, not a build recommendation." },
        { label: "Recommended action", text: "Track whether this format monetizes or stays a novelty." },
      ],
    };
  }

  return {
    mode: "heuristic",
    headline: `${text.slice(0, 110)}${text.length > 110 ? "…" : ""}`,
    bullets: [
      { label: "Key point", text: "No matched pattern yet — summary shows the raw caption." },
      { label: "Recommended action", text: "Open the source and tag it so future summaries improve." },
    ],
  };
}

/**
 * Batched Janice summaries: cached (memory + .hermes disk), one Gemini call for
 * all uncached posts, heuristic fallback when no GEMINI_API_KEY or the call fails.
 */
export async function getJaniceSummaries(posts: Post[]): Promise<Map<string, JaniceSummary>> {
  await loadDiskCache();
  const result = new Map<string, JaniceSummary>();
  const misses: Post[] = [];

  for (const post of posts) {
    const cached = memoryCache.get(post.id);
    if (cached && cached.mode === "llm") {
      result.set(post.id, cached);
    } else {
      misses.push(post);
    }
  }

  const { GEMINI_API_KEY } = getServerEnv();
  if (misses.length && GEMINI_API_KEY) {
    // Cap batch size to keep the prompt inside a sane token budget.
    const batch = misses.slice(0, 40);
    const payload = batch
      .map((post) => `id: ${post.id}\nsource: ${post.source} @${post.authorHandle}\ntext: ${post.text.replace(/\s+/g, " ").slice(0, 600)}`)
      .join("\n---\n");
    const response = await geminiGenerateText(
      GEMINI_API_KEY,
      [{ text: BATCH_PROMPT.replace("{POSTS}", payload) }],
      { temperature: 0.2, maxOutputTokens: 8000 },
    );
    if (response.ok) {
      const parsed = parseBatchResponse(response.text);
      for (const [id, summary] of parsed) {
        memoryCache.set(id, summary);
        result.set(id, summary);
      }
      if (parsed.size) {
        await persistDiskCache();
      }
    }
  }

  for (const post of posts) {
    if (!result.has(post.id)) {
      result.set(post.id, memoryCache.get(post.id) ?? heuristicSummary(post));
    }
  }

  return result;
}
